[version]
path = "src/pointers/version.py"

[envs.default]
dependencies = [
  "ward",
  "typing_extensions",
]
[envs.default.scripts]
tests = "ward --path tests/"

[envs.docs]
dependencies = [
  "mkdocs",
  "mkdocstrings[python]",
]
[envs.docs.scripts]
build = "mkdocs build --clean"
serve = "mkdocs serve --dev-addr localhost:8000"

[build.targets.wheel]
packages = ["src/pointers", "_pointers"]
