[version]
path = "src/pointers/version.py"

[envs.default]
dependencies = [
  "ward",
  "typing_extensions",
]
[envs.default.scripts]
tests = "ward"

[envs.docs]
dependencies = [
  "mkdocs",
]
[envs.docs.scripts]
build = "mkdocs build --clean"
serve = "mkdocs serve --dev-addr localhost:8000"

[[envs.test.matrix]]
python = ["37", "38", "39", "310"]

[build.targets.wheel]
packages = ["src/pointers", "_pointers"]
