name: CI

on:
    push:
        tags:
            - v*
        branches:
            - master
    pull_request:
        branches:
            - master

concurrency:
    group: build-${{ github.head_ref }}

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v3

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.8.1
              # env:
              #   CIBW_SOME_OPTION: value
              #    ...
              # with:
              #   package-dir: .
              #   output-dir: wheelhouse
              #   config-file: "{package}/pyproject.toml"

            - uses: actions/upload-artifact@v3
              with:
                  path: ./wheelhouse/*.whl

    publish:
        name: Publish release
        needs:
            - build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: artifacts
                  path: dist

            - name: Push build artifacts to PyPI
              uses: pypa/gh-action-pypi-publish@v1.5.1
              with:
                  skip_existing: true
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
